### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by ibarrajo**
Requires Cassandra 4.1.0 to run this example

### CODE REVIEW

**Review by eduyayo — APPROVED** [review]

**Comment by eduyayo** [comment]
please merge this pr, the compose won't boot up otherwise

**Comment by ibarrajo** [comment]
@frtelg is this good to merge? I don't have merge rights, feel free to do so if it's still applicable.

**Comment by eduyayo** [comment]
> @frtelg is this good to merge? I don't have merge rights, feel free to do so if it's still applicable.

Works for me!

**Comment by frtelg** [comment]
I'm sorry for my slow response... It is merged now.

**Pull request merged**
